env:
  global:
    - CI=false


services:
  - docker

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      before_install:
        - cd ./restful-web-services
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn test
      deploy:
        provider: script
        script: deploy_server.sh
        on:
          branch: travis
    - language: node_js
      node_js: stable
      before_install:
        - cd ./frontend/social-app
      install:
        - npm install
      script:
        - npm run build
        - npm run test

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL