env:
  global:
    - CI=false


services:
  - docker

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      before_install:
        - cd ./restful-web-services
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn test
        - cd ..
      after_success:
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - openssl aes-256-cbc -K $encrypted_a6a92fda07a4_key -iv $encrypted_a6a92fda07a4_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
        - gcloud version
        - tar -xzf credentials.tar.gz
        - gcloud auth activate-service-account --key-file client-secret.json
        - gcloud components install kubectl
        - gcloud config set project rmit-doughnuts
        - gcloud container clusters get-credentials
        - gcloud auth configure-docker
        - docker build -t gcr.io/rmit-doughnuts/b:$TRAVIS_BUILD_ID ./restful-web-services
        - pwd
        - gcloud config list --all
        - kubectl set image backend/backend master=gcr.io/rmit-dougnuts/b:$TRAVIS_BUILD_ID

    - language: node_js
      node_js: stable
      before_install:
        - cd ./frontend/social-app
      install:
        - npm install
      script:
        - npm run build
        - npm run test
        - cd ../..

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL