env:
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
  global:
    - CI=false

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      before_install:
        - cd ./restful-web-services
        - openssl aes-256-cbc -K $encrypted_a6a92fda07a4_key -iv $encrypted_a6a92fda07a4_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    - language: node_js
      node_js: stable
      before_install:
        - cd ./frontend/social-app
      install:
        - npm install
      script:
        - npm run build

deploy:
  provider: gae
  keyfile: client
  project: rmit-doughnuts

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL