env:
  global:
    - CI=false

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      before_install:
        - cd ./restful-web-services

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./frontend/social-app
      script:
        - npm run build
