apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: backend
  namespace: todos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: YOURDOCKERLOGINHERE/simple-app/simple-backend:latest
        ports:
        - containerPort: 3001

