apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todos
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    app: master
  type: LoadBalancer