apiVersion: v1
kind: Service
metadata:
  name: frontend-ser
  namespace: todos
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer