apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todos
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
  type: LoadBalancer
